logging:
  pattern:
    level: '%5p [%X{traceId}]'
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
  profiles:
    active: deb
  application:
    name: test
seata:
  enabled: false